#!/usr/bin/env groovy
pipeline {
  agent any

  stages {
    stage('Prepare') {
      steps {
        step([$class: 'WsCleanup'])
        checkout(scm)
        sh("""virtualenv -p python3.6 venv
        . venv/bin/activate
        pip install tox
        tox
        deactivate""")
      }
    }
    
    stage('Build artefact') {
      steps {
        sh('docker run -t -v $(pwd):/data amazonlinux:2018.03.0.20180424 /data/package.sh')
      }
    }
    
    stage('Generate sha256') {
      steps {
        sh('openssl dgst -sha256 -binary {{ cookiecutter.project_name }}.zip | openssl enc -base64 > {{ cookiecutter.project_name }}.zip.base64sha256')
      }
    }
    
    stage('Upload to s3') {
      steps {
        sh("""
		SANDBOX=platsec-deployment-artifacts-sandbox-93bc63e0b4
        PRODUCTION=platsec-deployment-artifacts-production-fd89784e59

        for bucket in "\${SANDBOX}" ; do
          aws s3 cp {{ cookiecutter.project_name }}.zip \
				"s3://\${bucket}/{{ cookiecutter.project_name }}.zip" \
			    --acl=bucket-owner-full-control

          aws s3 cp {{ cookiecutter.project_name }}.zip.base64sha256 \
				"s3://\${bucket}/{{ cookiecutter.project_name }}.zip.base64sha256" \
				--content-type text/plain --acl=bucket-owner-full-control
        done
        """)    
      }
    }
  }
}
