#!/usr/bin/env groovy
pipeline {
  agent any

  stages {
    stage('Prepare') {
      steps {
        step([$class: 'WsCleanup'])
        checkout(scm)
        sh("""virtualenv -p python3.6 venv
        . venv/bin/activate
        pip install tox
        tox
        deactivate""")
      }
    }
    stage('Build artefact') {
      steps {
        sh('docker run -t -v $(pwd):/data amazonlinux:2018.03.0.20180424 /data/package.sh')
      }
    }
    stage('Generate sha256') {
      steps {
        sh('openssl dgst -sha256 -binary {{cookiecutter.function_name}}.zip | openssl enc -base64 > {{cookiecutter.function_name}}.zip.base64sha256')
      }
    }
    stage('Upload to s3') {
      steps {
        sh("""for env in sandbox integration; do
                #development qa staging externaltest production; do
                aws s3 cp {{cookiecutter.function_name}}.zip s3://mdtp-lambda-functions-\${env}/{{cookiecutter.function_name}}.zip --acl=bucket-owner-full-control
                aws s3 cp {{cookiecutter.function_name}}.zip.base64sha256 s3://mdtp-lambda-functions-\${env}/{{cookiecutter.function_name}}.zip.base64sha256 --content-type text/plain --acl=bucket-owner-full-control
                done
        """)
      }
    }
  }
}
